<a href="https://colab.research.google.com/github/Alina-Shrestha/Final/blob/main/Alina_Shrestha_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Worksheet – 0

## Student: Alina Shrestha_2408564


This notebook contains solutions for:
1. Basic Vector and Matrix Operations with NumPy
2. Array Creation and Manipulation
3. Matrix Operations
4. Performance Comparison between Python Lists and NumPy Arrays**

In [ ]:
import numpy as np

**Problem 1: Array Creation**

In [ ]:
import numpy as np

# 1. Empty array 2x2
arr1 = np.empty((2,2))
print("Empty Array:\n", arr1)

# 2. All ones array 4x2
arr2 = np.ones((4,2))
print("\nOnes Array:\n", arr2)

# 3. Array filled with specific value
arr3 = np.full((3,3),7)
print("\nFull Array:\n", arr3)

# 4. Zeros array same shape as arr2
arr4 = np.zeros_like(arr2)
print("\nZeros like:\n", arr4)

# 5. Ones array same shape as arr1
arr5 = np.ones_like(arr1)
print("\nOnes like:\n", arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nList to Array:\n", arr6)

Empty Array:
 [[1.70481620e-315 0.00000000e+000]
 [4.94065646e-324 6.58922376e-310]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like:
 [[1. 1.]
 [1. 1.]]

List to Array:
 [1 2 3 4]


**Problem 2: Array Manipulation**

In [ ]:
# 1. Array from 10 to 49
arr = np.arange(10,50)
print("10 to 49:\n",arr)

# 2. 3x3 matrix from 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n",matrix)

# 3. Identity Matrix
identity = np.eye(3)
print("\nIdentity Matrix:\n",identity)

# 4. Random array size 30 + mean
rand_arr = np.random.random(30)
print("\nRandom Array Mean:", rand_arr.mean())

# 5. 10x10 random array min and max
rand_matrix = np.random.random((10,10))
print("\nMin:", rand_matrix.min())
print("Max:", rand_matrix.max())

# 6. Zero array size 10 replace 5th element
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\nReplace 5th element:\n",zero_arr)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
rev = arr[::-1]
print("\nReversed Array:\n",rev)

# 8. 2D array border 1 inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\nBorder Matrix:\n",border)

# 9. 8x8 checkerboard
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print("\nCheckerboard:\n",checker)

10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array Mean: 0.5497612457193843

Min: 0.03751307056971953
Max: 0.9837598584026118

Replace 5th element:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

Border Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem 3: Array Operations**

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Addition
print("Addition:\n", x+y)

# 2. Subtraction
print("\nSubtraction:\n", x-y)

# 3. Multiply with integer
print("\nMultiply with 3:\n", x*3)

# 4. Square each element
print("\nSquare:\n", x**2)

# 5. Dot product
print("\nDot product v.w:", np.dot(v,w))
print("Dot product x.v:", np.dot(x,v))
print("Dot product x.y:\n", np.dot(x,y))

# 6. Concatenate
print("\nConcatenate x and y (rows):\n", np.concatenate((x,y),axis=0))

print("\nConcatenate v and w (columns):\n", np.vstack((v,w)))

# 7. Concatenate x and v
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:",e)

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply with 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v: [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (columns):
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem 4: Matrix Operations**

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A,A_inv)

print("A * A^-1 =\n",identity)

# 2. Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB =\n",AB)
print("\nBA =\n",BA)

# 3. Prove (AB)^T = B^T A^T

left = (np.dot(A,B)).T
right = np.dot(B.T,A.T)

print("\n(AB)^T =\n",left)
print("\nB^T A^T =\n",right)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]


**Solve Linear Equations**

In [ ]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Inverse method
A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print("Solution [x,y,z]:\n",X)

Solution [x,y,z]:
 [ 2.  1. -2.]


**10.2 Experiment: How Fast is NumPy**

In [ ]:
import time
import numpy as np

**1. Element-wise Addition**

In [ ]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

print("Python List Addition Time:", time.time()-start)


# NumPy

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result = arr1 + arr2

print("NumPy Addition Time:", time.time()-start)

Python List Addition Time: 0.10945963859558105
NumPy Addition Time: 0.028751373291015625


**2. Element-wise Multiplication**

In [ ]:
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

print("Python Multiplication Time:", time.time()-start)


start = time.time()

result = arr1 * arr2

print("NumPy Multiplication Time:", time.time()-start)

Python Multiplication Time: 0.12860488891601562
NumPy Multiplication Time: 0.018723726272583008


**3. Dot Product**

In [ ]:
start = time.time()

dot = sum(list1[i]*list2[i] for i in range(size))

print("Python Dot Product Time:", time.time()-start)


start = time.time()

dot = np.dot(arr1,arr2)

print("NumPy Dot Product Time:", time.time()-start)

Python Dot Product Time: 0.13086271286010742
NumPy Dot Product Time: 0.0018999576568603516


**4. Matrix Multiplication**

In [ ]:
size = 200  # smaller size to avoid crashing Colab

A = np.random.rand(size,size)
B = np.random.rand(size,size)

start = time.time()

result = np.dot(A,B)

print("NumPy Matrix Multiplication Time:", time.time()-start)

NumPy Matrix Multiplication Time: 0.011318445205688477
